Repository dejan-xd-organization/NistagramOnlineAPI, pull requests merged in 2021-08, with the labels that each got.

#8 edit_user -> develop Close #6
  Controllers/OnlineController.cs
  NistagramOnlineAPI.csproj
  Service/IOnlineService.cs
  Service/Implementation/OnlineServiceImpl.cs
Labels: user story, pull request

#9 view_page -> develop Close #7
  Controllers/OnlineController.cs
  NistagramOnlineAPI.csproj
  Service/IOnlineService.cs
  Service/Implementation/OnlineServiceImpl.cs
Labels: user story, pull request

#10 sonar_cloud -> develop Close #5
  Controllers/OnlineController.cs
  Service/IOnlineService.cs
Labels: bug, documentation, pull request

#11 develop -> master Sprint 3 Release v1.0.2
  Controllers/OnlineController.cs
  NistagramOnlineAPI.csproj
  Service/IOnlineService.cs
  Service/Implementation/OnlineServiceImpl.cs
  Startup.cs
  appsettings.json
Labels: user story, pull request, release

#13 feature/chat -> develop Feature/chat
  Controllers/OnlineController.cs
  NistagramOnlineAPI.csproj
Labels: user story, pull request
